//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class dns_Clientes
    {
        public int IdCliente { get; set; }
        public string Razon_Social { get; set; }
        public string Direccion { get; set; }
        public string Contacto { get; set; }
        public string CUIT { get; set; }
        public string Telefono_Contacto { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> idClientMovimiento { get; set; }
        public string COD_CLIENT { get; set; }
    }
}
