//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class dns_SolicitudEstado
    {
        public int idEstado { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Order { get; set; }
        public string Descripcion { get; set; }
    }
}
