//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class dns_SolicitudLote
    {
        public int IdLote { get; set; }
        public int IdCliente { get; set; }
        public string NroLote { get; set; }
        public System.DateTime FechaLote { get; set; }
        public Nullable<System.DateTime> FechaVencim { get; set; }
        public string Periodo { get; set; }
        public string Ubic_Origen { get; set; }
        public string Ubic_Destino { get; set; }
        public string TITULO { get; set; }
        public int IdTipoPresupuesto { get; set; }
        public int IdEstado { get; set; }
        public string Solicito { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> ValorInicial { get; set; }
        public string Fullname { get; set; }
        public string Archivo { get; set; }
        public byte[] ArchivoObject { get; set; }
        public string ArchivoSize { get; set; }
        public Nullable<int> IdAuxiliarCC { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
        public string ModificadoPor { get; set; }
    }
}
