//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudesDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aDbDEINOSCloud_DevEntities : DbContext
    {
        public aDbDEINOSCloud_DevEntities()
            : base("name=aDbDEINOSCloud_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dns_Clientes> dns_Clientes { get; set; }
        public virtual DbSet<dns_Solicitud> dns_Solicitud { get; set; }
        public virtual DbSet<dns_SolicitudEstado> dns_SolicitudEstado { get; set; }
        public virtual DbSet<dns_SolicitudLote> dns_SolicitudLote { get; set; }
    }
}
